name: Docker Image
on:
  push:
    tags:
      - 0.*
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: Docker Image
          release_name: Docker Image
          draft: true
          prerelease: true
  build:
    name: Build
    needs: release
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v3
      - name: Build
        run: docker build . --file Dockerfile --tag doandat943/x-ui-en
        
      - name: Package
        run: docker save doandat943/x-ui-en | gzip > x-ui-en-docker.tar.gz
        
      - name: Upload
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: x-ui-en-docker.tar.gz
          asset_name: x-ui-en-docker.tar.gz
          asset_content_type: application/gzip
